//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>[uBlogsy] RSS</summary>
	[PublishedContentModel("uBlogsyRSS")]
	public partial class UBlogsyRss : UBlogsyBaseDocType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "uBlogsyRSS";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public UBlogsyRss(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<UBlogsyRss, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Copyright: Copyright information which is shown in your RSS feed.    e.g Mid-code Crisis  
		///</summary>
		[ImplementPropertyType("uBlogsyRssCopyright")]
		public string UBlogsyRssCopyright
		{
			get { return this.GetPropertyValue<string>("uBlogsyRssCopyright"); }
		}

		///<summary>
		/// Description: The description of your RSS feed
		///</summary>
		[ImplementPropertyType("uBlogsyRssDescription")]
		public string UBlogsyRssDescription
		{
			get { return this.GetPropertyValue<string>("uBlogsyRssDescription"); }
		}

		///<summary>
		/// Title: The title which is shown in your RSS feed
		///</summary>
		[ImplementPropertyType("uBlogsyRssTitle")]
		public string UBlogsyRssTitle
		{
			get { return this.GetPropertyValue<string>("uBlogsyRssTitle"); }
		}
	}
}
