//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>[uBlogsy] [Base] Page</summary>
	[PublishedContentModel("uBlogsyBasePage")]
	public partial class UBlogsyBasePage : UBlogsyBaseDocType
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "uBlogsyBasePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public UBlogsyBasePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<UBlogsyBasePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Body
		///</summary>
		[ImplementPropertyType("uBlogsyContentBody")]
		public IHtmlString UBlogsyContentBody
		{
			get { return this.GetPropertyValue<IHtmlString>("uBlogsyContentBody"); }
		}

		///<summary>
		/// Summary
		///</summary>
		[ImplementPropertyType("uBlogsyContentSummary")]
		public string UBlogsyContentSummary
		{
			get { return this.GetPropertyValue<string>("uBlogsyContentSummary"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("uBlogsyContentTitle")]
		public string UBlogsyContentTitle
		{
			get { return this.GetPropertyValue<string>("uBlogsyContentTitle"); }
		}

		///<summary>
		/// Navigation Title
		///</summary>
		[ImplementPropertyType("uBlogsyNavigationTitle")]
		public string UBlogsyNavigationTitle
		{
			get { return this.GetPropertyValue<string>("uBlogsyNavigationTitle"); }
		}

		///<summary>
		/// Description: Used for meta description. When this is empty, an exerpt of the body text of the page is used.
		///</summary>
		[ImplementPropertyType("uBlogsySeoDescription")]
		public string UBlogsySeoDescription
		{
			get { return this.GetPropertyValue<string>("uBlogsySeoDescription"); }
		}

		///<summary>
		/// Keywords: Used for meta keywords. When this is empty, the title of the page is used.
		///</summary>
		[ImplementPropertyType("uBlogsySeoKeywords")]
		public string UBlogsySeoKeywords
		{
			get { return this.GetPropertyValue<string>("uBlogsySeoKeywords"); }
		}

		///<summary>
		/// Seo Title
		///</summary>
		[ImplementPropertyType("uBlogsySeoTitle")]
		public string UBlogsySeoTitle
		{
			get { return this.GetPropertyValue<string>("uBlogsySeoTitle"); }
		}
	}
}
