//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>[uBlogsy] Landing</summary>
	[PublishedContentModel("uBlogsyLanding")]
	public partial class UBlogsyLanding : UBlogsyBasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "uBlogsyLanding";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public UBlogsyLanding(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<UBlogsyLanding, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Blog Roll Links: A list of blogs you want to follow. Make sure it's one per line.    e.g   http://feeds.feedburner.com/midcodecrisis  http://feeds.feedburner.com/umbracoblog
		///</summary>
		[ImplementPropertyType("uBlogsyBlogLinks")]
		public string UBlogsyBlogLinks
		{
			get { return this.GetPropertyValue<string>("uBlogsyBlogLinks"); }
		}

		///<summary>
		/// Default Author: This author is used when none are defined in a post.
		///</summary>
		[ImplementPropertyType("uBlogsyGeneralDefaultAuthor")]
		public IEnumerable<IPublishedContent> UBlogsyGeneralDefaultAuthor
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("uBlogsyGeneralDefaultAuthor"); }
		}

		///<summary>
		/// Show Social Media Links: Select this to show social media sharing links under each post.
		///</summary>
		[ImplementPropertyType("uBlogsyGeneralShowSocialMedia")]
		public bool UBlogsyGeneralShowSocialMedia
		{
			get { return this.GetPropertyValue<bool>("uBlogsyGeneralShowSocialMedia"); }
		}

		///<summary>
		/// Use Summary On Landing: Select this to use post summaries on the main page, instead of whole posts.  
		///</summary>
		[ImplementPropertyType("uBlogsyGeneralUseSummary")]
		public bool UBlogsyGeneralUseSummary
		{
			get { return this.GetPropertyValue<bool>("uBlogsyGeneralUseSummary"); }
		}

		///<summary>
		/// Use Title As Node Name: Deselect this if you want to have a post title which is different to your post's node name.    eg. If you want your title to be "My title" but you want the post url to be /posts/2011/01/my-cool-title/ instead of /posts/2011/01/my-title/    Selected by default.
		///</summary>
		[ImplementPropertyType("uBlogsyGeneralUseTitleAsNodeName")]
		public bool UBlogsyGeneralUseTitleAsNodeName
		{
			get { return this.GetPropertyValue<bool>("uBlogsyGeneralUseTitleAsNodeName"); }
		}
	}
}
