//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>[uBlogsy] Post</summary>
	[PublishedContentModel("uBlogsyPost")]
	public partial class UBlogsyPost : UBlogsyBasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "uBlogsyPost";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public UBlogsyPost(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<UBlogsyPost, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Author: There can be multiple authors separated by ",".
		///</summary>
		[ImplementPropertyType("uBlogsyPostAuthor")]
		public IEnumerable<IPublishedContent> UBlogsyPostAuthor
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("uBlogsyPostAuthor"); }
		}

		///<summary>
		/// Post Date
		///</summary>
		[ImplementPropertyType("uBlogsyPostDate")]
		public DateTime UBlogsyPostDate
		{
			get { return this.GetPropertyValue<DateTime>("uBlogsyPostDate"); }
		}

		///<summary>
		/// Disable Comments: Allows you to disable comments to this post. Note that comments that already exist will remain viewable.    If you do not have the comments extension installed, then you can delete this property.  
		///</summary>
		[ImplementPropertyType("uBlogsyPostDisableComments")]
		public bool UBlogsyPostDisableComments
		{
			get { return this.GetPropertyValue<bool>("uBlogsyPostDisableComments"); }
		}

		///<summary>
		/// Main Image
		///</summary>
		[ImplementPropertyType("uBlogsyPostImage")]
		public string UBlogsyPostImage
		{
			get { return this.GetPropertyValue<string>("uBlogsyPostImage"); }
		}

		///<summary>
		/// Categories
		///</summary>
		[ImplementPropertyType("uBlogsyPostLabels")]
		public IEnumerable<IPublishedContent> UBlogsyPostLabels
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("uBlogsyPostLabels"); }
		}

		///<summary>
		/// Tags: Remember to click save (or publish)!
		///</summary>
		[ImplementPropertyType("uBlogsyPostTags")]
		public object UBlogsyPostTags
		{
			get { return this.GetPropertyValue("uBlogsyPostTags"); }
		}
	}
}
